export const Filmlist =[
    {id: 1, tilte: 'Transformers', year: '2007', img:'./image/pic1.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film1'},
    {id: 2, tilte: 'Transformers: Revenge of the Fallen', year: '2009', img:'./image/pic1.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film2'},
    {id: 3, tilte: 'Transformers: Dark of the Moon', year: '2011', img:'./image/pic1.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film3'},
    {id: 4, tilte: 'Transformers: Age of Extinction', year: '2014',img:'./image/pic1.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film4'},
    {id: 5, tilte: 'Bumblebee', year: '2018',img:'./image/pic1.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film5' },
    {id: 6, tilte: 'Transformers: Rise of the Beast', year: '2023 ', img:'./image/pic1.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film6'}
  ];
  export const RecommendFilm =[
    {id: 1, tilte: 'Avatar 1', year: '2007', img:'./image/pic2.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film'},
    {id: 2, tilte: 'Avatar 2', year: '2009', img:'./image/pic2.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film'},
    {id: 3, tilte: 'Avatar 3', year: '2011', img:'./image/pic2.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film'},
    {id: 4, tilte: 'Avatar 4', year: '2014',img:'./image/pic2.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film'},
    {id: 5, tilte: 'Avatar 5', year: '2018',img:'./image/pic2.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film' },
    {id: 6, tilte: 'Avatar 6', year: '2023 ', img:'./image/pic2.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film'}
  ];