export const Filmlist =[
    {id: 1, cost: 10000,src:'https://www.youtube.com/embed/v8ItGrI-Ou0' , tilte: 'Transformers', year: '2007', img:'./image/pic1.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film1'},
    {id: 2, cost: 10000,src:'https://www.youtube.com/embed/fnXzKwUgDhg' , tilte: 'Transformers: Revenge of the Fallen', year: '2009', img:'./image/hi3.png',nation:'USA',info:'Nhã nhạc cung đình Huế là thể loại nhạc của cung đình thời phong kiến, được biểu diễn vào các dịp lễ hội (vua đăng quang, băng hà, các lễ hội tôn nghiêm khác) trong năm của các triều đại nhà Nguyễn của Việt Nam.[1] Nhã nhạc cung đình Huế đã được UNESCO công nhận là Kiệt tác truyền khẩu và phi vật thể nhân loại vào năm 2003.[2].'},
    {id: 3, cost: 10000,src:'https://www.youtube.com/embed/itnqEauWQZM' , tilte: 'Transformers: Dark of the Moon', year: '2011', img:'./image/tranf.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film3'},
    {id: 4, cost: 10000,src:'https://youtu.com/embed/C3GouGa0noM' , tilte: 'Transformers: Age of Extinction', year: '2014',img:'./image/blue-aesthetic-moon-df8850p673zj275y.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film4'},
    {id: 5, cost: 10000,src:'https://youtu.com/embed/C3GouGa0noM' , tilte: 'Bumblebee', year: '2018',img:'./image/bumblebee-1280a-15436251734471280w-15444930656192129787876.webp',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film5' },
    {id: 6, cost: 10000,src:'https://youtu.com/embed/C3GouGa0noM' , tilte: 'Transformers: Rise of the Beast', year: '2023 ', img:'./image/tran4.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film6'},
    {id: 7, cost: 10000,src:'https://youtu.com/embed/C3GouGa0noM' , tilte: 'Transformers 7', year: '2007', img:'./image/pic1.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film1'},
    {id: 8, cost: 10000,src:'https://youtu.be/C3GouGa0noM2' , tilte: 'Transformers 8: Revenge of the Fallen', year: '2009', img:'./image/pic1.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film2'},
    {id: 9, cost: 10000,src:'https://youtu.be/C3GouGa0noM3' , tilte: 'Transformers 9: Dark of the Moon', year: '2011', img:'./image/pic1.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film3'},
    {id: 10, cost: 10000,src:'https://youtu.be/C3GouGa0noM4' , tilte: 'Transformers 10: Age of Extinction', year: '2014',img:'./image/pic1.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film4'},
    {id: 11, cost: 10000,src:'https://youtu.be/C3GouGa0noM5' , tilte: 'Bumblebee 2', year: '2018',img:'./image/pic1.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film5' },
    {id: 12, cost: 10000,src:'https://youtu.be/C3GouGa0noM6' , tilte: 'Transformers 11: Rise of the Beast', year: '2023 ', img:'./image/pic1.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film6'}
  ];
  export const RecommendFilm =[
    {id: 1, cost: 10000,src:'https://youtu.be/C3GouGa0noM' , tilte: 'Avatar 1', year: '2007', img:'./image/pic2.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film'},
    {id: 2, cost: 10000,src:'https://youtu.be/C3GouGa0noM' , tilte: 'Avatar 2', year: '2009', img:'./image/pic2.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film'},
    {id: 3, cost: 10000,src:'https://youtu.be/C3GouGa0noM' , tilte: 'Avatar 3', year: '2011', img:'./image/pic2.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film'},
    {id: 4, cost: 10000,src:'https://youtu.be/C3GouGa0noM' , tilte: 'Avatar 4', year: '2014',img:'./image/pic2.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film'},
    {id: 5, cost: 10000,src:'https://youtu.be/C3GouGa0noM' , tilte: 'Avatar 5', year: '2018',img:'./image/pic2.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film' },
    {id: 6, cost: 10000,src:'https://youtu.be/C3GouGa0noM' , tilte: 'Avatar 6', year: '2023 ', img:'./image/pic2.jpg',nation:'USA',info:'Bumblebee (marketed as Transformers: Bumblebee)[7][8][9] is a 2018 science fiction action film based on the Hasbro and Takara Tomy"s Transformers toy line character of the same name. It is the sixth installment in the Transformers film series, serving as a spin-off and prequel to the 2007 film'}
  ];